### ISSUE TITLE
credit or debit card option not coming android

### ISSUE THREAD

**Issue by mayur2345** [wgltony/react-native-braintree-dropin-ui#53] opened 2020-09-14 17:43 UTC
Credit or debit card option is coming for ios but it is not coming for android.

**Comment by kishanbharda** [comment] 2020-09-15 06:28
Duplicate of #52

**Comment by kishanbharda** [comment] 2020-09-15 06:29
I think you have already solve it. Please close this issue.

**Comment by mayur2345** [comment] 2020-09-16 13:37
solved 
https://github.com/wgltony/react-native-braintree-dropin-ui/issues/52

**Closed** 2020-09-16 13:37 UTC
